apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: python-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Zaid2044/multitier-eks-gitops.git
    targetRevision: main
    path: helm/python-app

  destination:
    server: https://kubernetes.default.svc
    namespace: python

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true