namespace: java
backend:
  image:
    repository: 234273295663.dkr.ecr.ap-south-1.amazonaws.com/java-backend
    tag: f8b2366
frontend:
  image:
    repository: 234273295663.dkr.ecr.ap-south-1.amazonaws.com/java-frontend
    tag: f8b2366
postgres:
  image: postgres:17.5-alpine
database:
  name: employee_portal
  user: employee_app
  password: employee_secret
storage:
  size: 5Gi
  storageClass: gp2
