apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: nodejs-backend
  namespace: monitoring

spec:
  namespaceSelector:
    matchNames:
      - nodejs

  selector:
    matchLabels:
      app: backend

  endpoints:
    - port: http
      path: /metrics
      interval: 30s