namespace: nodejs
backend:
  image:
    repository: 234273295663.dkr.ecr.ap-south-1.amazonaws.com/nodejs-backend
    tag: e0ef2dc
frontend:
  image:
    repository: 234273295663.dkr.ecr.ap-south-1.amazonaws.com/nodejs-frontend
    tag: e0ef2dc
postgres:
  image: postgres:16-alpine
database:
  name: taskflow
  user: taskflow_user
  password: taskflow_pass
storage:
  size: 5Gi
  storageClass: gp2
