apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          ports:
            - containerPort: 5000

          env:
            - name: DATABASE_URL
              value: "postgresql://inventory_user:inventory_pass@database:5432/inventory_db"

            - name: SECRET_KEY
              value: "inventory-secret"

            - name: FLASK_DEBUG
              value: "false"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 20

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 30